"""Sidecar subtitle discovery — used by the pipeline when ffprobe finds zero
embedded sub tracks. Real-world example: external .srt files generated by
Plex/Emby or downloaded via Bazarr that live next to the .mkv."""

from pathlib import Path

from server.subs.pipeline import _find_sidecar_subtitle, _parse_sidecar_lang


def _write_empty(p: Path) -> None:
    p.write_text("")


def test_parse_sidecar_lang_unflagged_returns_none():
    assert _parse_sidecar_lang("") is None


def test_parse_sidecar_lang_plain_lang():
    assert _parse_sidecar_lang("en") == "en"
    assert _parse_sidecar_lang("jpn") == "jpn"


def test_parse_sidecar_lang_lang_plus_flag():
    # `.en.hi.srt` — `hi` is a flag (hearing-impaired) when preceded by a lang
    assert _parse_sidecar_lang("en.hi") == "en"


def test_parse_sidecar_lang_pure_flag_returns_none():
    assert _parse_sidecar_lang("forced") is None
    assert _parse_sidecar_lang("sdh") is None
    assert _parse_sidecar_lang("cc") is None


def test_parse_sidecar_lang_lone_hi_treated_as_hindi():
    # Ambiguous: `.hi.srt` — only token. We treat it as Hindi (ISO 639-1).
    assert _parse_sidecar_lang("hi") == "hi"


def test_find_sidecar_skips_target_lang(tmp_path: Path):
    """If the only sidecar IS in target_lang, no translation needed -> None."""
    media = tmp_path / "Movie.mkv"
    _write_empty(media)
    _write_empty(tmp_path / "Movie.en.srt")
    assert _find_sidecar_subtitle(media, "en") is None


def test_find_sidecar_picks_non_target_lang(tmp_path: Path):
    media = tmp_path / "Movie.mkv"
    _write_empty(media)
    ru = tmp_path / "Movie.ru.srt"
    _write_empty(ru)
    result = _find_sidecar_subtitle(media, "en")
    assert result is not None
    assert result.path == ru
    assert result.lang == "ru"


def test_find_sidecar_prefers_plain_over_flagged(tmp_path: Path):
    """Given .ru.srt AND .ru.hi.srt, prefer the plain (non-HI) one."""
    media = tmp_path / "Movie.mkv"
    _write_empty(media)
    plain = tmp_path / "Movie.ru.srt"
    hi = tmp_path / "Movie.ru.hi.srt"
    _write_empty(plain)
    _write_empty(hi)
    result = _find_sidecar_subtitle(media, "en")
    assert result is not None
    assert result.path == plain


def test_find_sidecar_iso639_2_alias_matches_target(tmp_path: Path):
    """Sidecar tagged `eng` should be recognized as English when target=en."""
    media = tmp_path / "Movie.mkv"
    _write_empty(media)
    _write_empty(tmp_path / "Movie.eng.srt")
    # eng is the ISO 639-2 form of en — we should treat as target.
    assert _find_sidecar_subtitle(media, "en") is None


def test_find_sidecar_unlabeled_picked_when_no_target_match(tmp_path: Path):
    """An unlabeled .srt is picked if no other candidate exists. Its lang is None."""
    media = tmp_path / "Movie.mkv"
    _write_empty(media)
    plain = tmp_path / "Movie.srt"
    _write_empty(plain)
    result = _find_sidecar_subtitle(media, "en")
    assert result is not None
    assert result.path == plain
    assert result.lang is None


def test_find_sidecar_returns_none_when_no_match(tmp_path: Path):
    media = tmp_path / "Movie.mkv"
    _write_empty(media)
    # Unrelated file with similar name but not a sidecar — different basename
    _write_empty(tmp_path / "Trailer.ru.srt")
    assert _find_sidecar_subtitle(media, "en") is None


def test_find_sidecar_adventure_time_real_case(tmp_path: Path):
    """Reproduces the actual user case: Adventure Time S01E04 with .en.hi.srt.

    Emby tags this as Hindi (because .hi is the hearing-impaired marker on
    an English file, but it's been used loosely in the wild). The sidecar
    discovery should pick this file when target=en."""
    media = tmp_path / "Adventure Time - S01E04 - Tree Trunks Bluray-720p.mkv"
    _write_empty(media)
    sidecar = tmp_path / "Adventure Time - S01E04 - Tree Trunks Bluray-720p.en.hi.srt"
    _write_empty(sidecar)
    # When user asks for `en`, this file IS English (lang=en, flag=hi);
    # we treat lang=en as target, so the file is excluded -> no candidates.
    # User would need to provide source_lang explicitly or check the file
    # content. This is a real edge case in our filename grammar.
    assert _find_sidecar_subtitle(media, "en") is None
    # But when target=ru, the .en.hi sidecar IS a non-target candidate:
    result = _find_sidecar_subtitle(media, "ru")
    assert result is not None
    assert result.path == sidecar
